#!/usr/bin/env bash

# My tool for launching and debugging live image
# Seems like it don't need many comments for now due to self-documented and simple design

set -eu

mediatype='cdrom'
image=''


print_help() {
local usagetext
    read -r -d '' usagetext <<EOF || true
Usage:
    run_iso [options]

Options:
    No options but -h and -i for yet now
    Contribute to the project!!!
    *sounds of terrifying keystrokes*

Example:
    Run an image:
    $ run_iso misha_image.iso
EOF
    printf '%s\n' "${usagetext}"
}

run_image() {
    #pretty simple for now
    qemu-system-x86_64 -cdrom ./${image} -net user -daemonize
}

#arguments parsing
if (( ${#@} > 0 )); then
    while getopts 'hi:' flag; do
        case "$flag" in
            h)
                print_help
                exit 0
                ;;
            i)
                image="$OPTARG"
                ;;
            *)
                printf '%s\n' "Error: Wrong option. Try 'run_iso -h'."
                exit 1
                ;;
        esac
    done
else
    print_help
    exit 1
fi

run_image
